spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wayroc_chatbot?serverTimezone=UTC&useSSL=false
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 8080
